### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by gmuraru** [gmuraru/MiceNDemons#11]
Add GitHub action to run the tests for Trie from the Python package (with coverage report and also fail if coverage if < 100%)

**Comment by tullur** [comment]
Hi, I'll do this.

**Comment by gmuraru** [comment]
Great! Adding you to this issue.

**Comment by tullur** [comment]
Hey @gmuraru! Workflow is ready, coverage example: 
![image](https://user-images.githubusercontent.com/21138508/95027545-039cac00-06a2-11eb-9731-0725db5ccc5a.png)

**Comment by gmuraru** [comment]
Hey @tullur could you add it to target only Languages/Python folder?
Currently, it seems that if I add another folder in Languages (and I add there python tests - that would also be taken into consideration).

**Comment by gmuraru** [comment]
Let me merge my PR such that trie.py is covered 100%

**Comment by tullur** [comment]
> Hey @tullur could you add it to target only Languages/Python folder?
> Currently, it seems that if I add another folder in Languages (and I add there python tests - that would also be taken into consideration).

Yep, of course, I'll add it to target only Languages/Python.

**Comment by gmuraru** [comment]
Thank you! :100:

**Comment by gmuraru** [comment]
Closed by #14
