### ISSUE TITLE
Make and add logo in README.md

### ISSUE THREAD

**Issue by gmuraru** [gmuraru/MiceNDemons#22]
# Description

Create a logo with some mice and demons in a cartoon/anime like style.
* One idea is to have the first layer with some mice and then another one (behind them) with some dragons. The Dragons would look bigger than the mice.
* And probably the logo somewhere up

**Comment by vanntile** [comment]
I'd like to contribute on this issue

**Comment by gmuraru** [comment]
Great! Assigned you to it :+1:

**Comment by vanntile** [comment]
![Screenshot from 2020-10-07 19-46-06](https://user-images.githubusercontent.com/33692650/95361776-d59fad80-08d5-11eb-8245-26b20a03d3a8.png)

For a cartoonish look, without other specs, this would be a direction. Depending on the feedback on this, I'll update the design an PR.

**Request** a color palette: would a dark or light palette desired? right now it's neither. A grey palette with a tint of red and black is my recommendation.

**Comment by gmuraru** [comment]
This is great! Could you add a darker pallet (only to see how it look).

Thank you again :D

**Comment by vanntile** [comment]
![Frame 2](https://user-images.githubusercontent.com/33692650/95476424-e7de2200-098f-11eb-93b2-7cf9765634dd.png)

I think this second version would be more suitable.

**Comment by gmuraru** [comment]
Yep! Thank you a lot!

Could you open a PR to add it in the Readme? (also I will tag the PR with the hacktoberfest label)
